config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations", passwords: "passwords"}
  get 'about' => 'welcome#about'
  get 'donate' => 'welcome#donate'
  get 'contact' => 'welcome#contact'
  get 'welcome' => 'welcome#index'
  resources :secrets
  get "/help/:page" => "help#show"
  
  devise_scope :user do
    get '/signout', to: 'sessions#destroy', as: :signout
  end
  
  root to: 'welcome#index'
  
  

end

app/models/secret.rb
class Secret < ActiveRecord::Base
  
  #Relationships
  belongs_to :user
  
  #Validation
  validates :catname, presence: true 
  validates :description, presence: true
  
  #Thread.current[:session][:pin] #From login screen.  Must not be saved to DB "1234"
  
  #Encrypt fields with the help of attr_encrypted gem 
  #See https://github.com/attr-encrypted/attr_encrypted for details
  attr_encrypted :username,
                 :pw,
                 :url,
                 :notes,
                 :key =>  proc { ENV["encryption_key"] + Thread.current[:session][:pin] } 

  #proc forces the Thread.current[:session][:pin] to be evaluated each time
  #For production:  :key => proc { ENV["encryption_key"] + Thread.current[:session][:pin] }
  #For testing and seeding database:   :key => proc { ENV["encryption_key"] + "1234" }
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  
  before_action :set_record, except: [:index, :new, :create]
  before_action :authenticate_user!
  
  def new
    #Enforce maximum record count to prevent abuse and overuse
    if current_user.secrets.count >= 100
      flash[:notice] = "Maximum number of records exceeded."
      redirect_to secrets_path
    else
      @secret = Secret.new
    end
    
  end

  def create
     #@secret = Secret.new(secret_params)
     @secret =current_user.secrets.build(secret_params)
    
    if @secret.save
      flash[:notice] = "Saved"
      redirect_to secrets_path
    else
      flash[:error] = @secret.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    @secret.assign_attributes(secret_params)
     if @secret.save
       flash[:notice] = "Record was updated."
      redirect_to secrets_path 
     else
       flash[:error] = @secret.errors.full_messages.to_sentence
       render :edit
     end
  end

  def edit
    # Render the edit view
  end

  def destroy
    @secret = Secret.find(params[:id])
     if @secret.destroy
       flash[:notice] = "Record was deleted successfully."
       redirect_to action: :index
     else
       flash[:error] = "There was an error deleting the record."
       render :show
     end
  end

  def index
    #Rails.logger.info ">>>>> pin: #{session[:pin]}"
   begin
   #Catch decryption error
   #Try to decrypt a field to make sure encryption key and pin are correct
   current_user.secrets.first.pw if current_user.secrets.any?
   rescue Exception => e
    if e.message == "bad decrypt"
      flash[:error] = "Unable to decrypt.  Log in again with the correct PIN."
      Rails.logger.info ">>>> flash: #{flash.inspect}"
      redirect_to signout_path
      #redirect_to root_path
      #redirect_to destroy_user_session_path, method: :delete
      
    end
   end
   @secrets_grid = initialize_grid(current_user.secrets,
                    name:                 'g1',
                    order:                'secrets.catname',
                    order_direction:      'asc',
                    per_page:             10,
                    enable_export_to_csv: true,
                    csv_file_name:        'bSecure_Export'
                    )
      export_grid_if_requested('g1' => 'secrets_grid')
  end

  def show
    # Render the show view
  end
  
  
  private
  
  def set_record
    @secret = Secret.find(params[:id])
  end
  
  def secret_params
    params.require(:secret).permit(:catname, :description, :username, :url, :notes, :pw )
  end
  
end

app/helpers/secret_helper.rb
module SecretHelper
  
  #Reduce the field size to fit in the grid.  Used in secrets/index.html.erb
  def formatField(maxSize, fvalue)
    if fvalue
      #Only show the first max_size characters
      fvalue.length > maxSize ? fvalue[0, maxSize] + "..." : fvalue
    end
  end
end

app/views/secrets/_form.html.erb
<!--Used in Edit and New Views-->
<%= form_for @secret do |f| %>
  <div class="form-group">
    <%= f.label 'Type' %> <em>(Required, Not encrypted)</em><br/>
    <%= f.select :catname, ["Password", "CreditCard", "SerialNumber", "WebLogin", "Other"], class: 'form-control',autofocus: true, include_blank: true %> <br />

    <%= f.label 'Description' %> <em>(Required, Not encrypted)</em><br />
    <%= f.text_field :description,                 class: 'form-control', placeholder: "Enter the description", id: "Description" %>
    
    <%= f.label :username %>
    <%= f.text_field :username,                    class: 'form-control', placeholder: "Enter the username", id: "Username" %>
    
    <%= f.label 'Password' %>
    <%= f.text_field :pw,                          class: 'form-control', placeholder: "Enter the password", id: "Password" %>
    
    <%= f.label :url %>
    <%= f.text_field :url,                         class: 'form-control', placeholder: "Enter the URL", id: "Url" %>
    
    <%= f.label :notes %>
    <%= f.text_area :notes,                        class: 'form-control', placeholder: "Enter notes content", size: "25x3", id: "Notes" %>
    
    <p><a href="https://en.wikipedia.org/wiki/Markdown" target="_blank">[Markdown Help]</a> - **bold** _italic_ `code` >quote * - bullet list  </p>
  </div>
  <%= f.submit "Save", class: 'btn btn-primary' %>
  <%= link_to "Cancel", secrets_path, class: 'btn btn-default' %>

<% end %>

app/views/secrets/_form_tips.html.erb
<p><b>Tips</b></p>
<ul>
  <li>'Type', 'Description' are <b>not</b> encrypted.</li>
  <li>Format 'Notes' field with <a href="https://en.wikipedia.org/wiki/Markdown" target="_blank">Markdown</a></li>
</ul>

app/views/secrets/_secrets_grid.html.erb
<%= grid(@secrets_grid, show_filters: :when_filtered) do |g|

g.column name: 'Category', attribute: 'catname', custom_filter: :auto do |secret|
  secret.catname
end

g.column name: 'Description', attribute: 'description' do |secret|
  secret.description
end

g.column name: 'Username', attribute: 'username' do |secret|
  secret.username
end

g.column name: 'Password', attribute: 'pw' do |secret|
  secret.pw
end

g.column name: 'URL', attribute: 'url' do |secret|
  secret.url
end

g.column name: 'Notes', attribute: 'notes' do |secret|
  secret.notes
end

end -%>

app/views/secrets/create.html.erb
<h1>Secret#create</h1>
<p>Find me in app/views/secret/create.html.erb</p>

app/views/secrets/destroy.html.erb
<h1>Secret#destroy</h1>
<p>Find me in app/views/secret/destroy.html.erb</p>

app/views/secrets/edit.html.erb
<h1>Edit</h1>
 <div class="row">
   <div class="col-md-4">
     <p><b>Created</b></p>
     <%= @secret.created_at.in_time_zone('Eastern Time (US & Canada)').strftime("%Y-%m-%d at %I:%M%p") %> <br/>
     <br/>
     <p><b>Updated</b></p>
     <%= @secret.updated_at.in_time_zone('Eastern Time (US & Canada)').strftime("%Y-%m-%d at %I:%M%p") %> <br /><br />
     <%= render "form_tips" %>
   </div>
   <div class="col-md-8">
    <%= render "form" %>
   </div>
 </div>

app/views/secrets/index.html.erb
<%= grid(@secrets_grid, show_filters: :when_filtered) do |g|
  
  g.column do |secret|
    link_to("", edit_secret_path(secret), class: 'glyphicon glyphicon-pencil')
  end

  g.column name: 'CATEGORY', attribute: 'catname', custom_filter: :auto do |secret|
    secret.catname
  end
  
  g.column name: 'DESCRCIPTION', attribute: 'description' do |secret|
    if secret.description
      formatField(15, secret.description)
    end
  end
  
  g.column name: 'USERNAME', attribute: 'username', ordering: false, filter: false do |secret|
    formatField(15,secret.username)
  end
  
  g.column name: 'PASSWORD', attribute: 'pw', ordering: false, filter: false do |secret|
    formatField(10,secret.pw)
  end
  
  g.column name: 'URL', attribute: 'url', ordering: false, filter: false do |secret|
    formatField(15,secret.url)   
  end
  
  g.column name: 'NOTES', attribute: 'notes', ordering: false, filter: false do |secret|
    markdown(formatField(25,secret.notes))
  end
  
  g.column do |secret|
    link_to("", secret, method: :delete, class: 'glyphicon glyphicon-remove', data: { confirm: 'Are you sure you want to delete this record?' })
  end

end -%>

<%= link_to "New", new_secret_path, class: 'btn btn-primary' %>
<button class="wg-external-csv-export-button btn btn-primary" data-grid-name="g1">Export To CSV</button>

app/views/secrets/new.html.erb
<h1>New</h1>
 <div class="row">
   <div class="col-md-4">
     <%= render "form_tips" %>
   </div>
   <div class="col-md-8">
     <%= render "form" %>
   </div>
 </div>

app/views/secrets/show.html.erb
<% if @secret %>
<div>
  <p><%= @secret.catname %></p>
  <p><%= @secret.description %></p>
  <p><%= @secret.username %></p>
  <p><%= @secret.pw %></p>
  <p><%= @secret.url %></p>
  <p><%= @secret.notes %></p>
</div>
<% else %>
  <p>I couldn't find that record in your list.</p>
<% end %> 
  <%= link_to "Edit", edit_secret_path, class: 'btn btn-primary' %>
<%= link_to "Delete", @secret, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this record?' } %>

app/views/secrets/update.html.erb
<h1>Secret#update</h1>
<p>Find me in app/views/secret/update.html.erb</p>