config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations", passwords: "passwords"}
  get 'about' => 'welcome#about'
  get 'donate' => 'welcome#donate'
  get 'contact' => 'welcome#contact'
  get 'welcome' => 'welcome#index'
  resources :secrets
  get "/help/:page" => "help#show"
  
  devise_scope :user do
    get '/signout', to: 'sessions#destroy', as: :signout
  end
  
  root to: 'welcome#index'
  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <title>bSecure</title>
  </head>
    <div class = "container">
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span> 
            </button>  
            <%= link_to "bSecure", root_path, class: 'navbar-brand' %>
          </div> <!--/navbar-header -->
          
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
              <% if user_signed_in? %>
                <li><%= link_to "My Data", secrets_path %></li>
              <% end %>
              <li><%= link_to "Help", '/help/index' %></li>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Donate", donate_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
            </ul>    
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><%= link_to ' Edit-Profile', edit_user_registration_path, class: 'glyphicon glyphicon-cog'  %></li>
                <li><%= link_to " Log-Out", destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out' %></li>
              <% else %>
                <li><%= link_to " Sign-Up", new_user_registration_path, class: 'glyphicon glyphicon-user' %></li>
                <li><%= link_to " Log-In", new_user_session_path, class: 'glyphicon glyphicon-log-in' %></li>
              <% end %>  
            </ul>
          </div> <!-- navbar collapse -->
        </div> <!--/.container-fluid -->
      </nav>
      
      <div class="flash">
        <% if flash[:notice] %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
             <%= flash[:notice] %>
           </div>
        <% elsif flash[:error] %>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:error] %>
          </div>
        <% elsif flash[:alert] %>
          <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
        <% end %>
      </div> <!--/flash -->
      <%= yield %>
    </div> <!--/container -->
  </body>
</html>